CREATE DATABASE ThuVien
Go
USE ThuVien
GO
--Tao bang bo phan
CREATE TABLE [BOPHAN](
 [MaBoPhan] [int] NOT NULL,
 [TenBoPhan] [nvarchar]
(40) NULL,
CONSTRAINT [PK_BOPHAN] PRIMARY KEY(MaBoPhan)
)
GO
--Tao bang doc gia
CREATE TABLE [LOAIDOCGIA](
 [MaLoaiDocGia] [int] NOT NULL,
 [TenLoaiDocGia] [nvarchar]
(50) NULL,
CONSTRAINT [PK_DOCGIA] PRIMARY KEY(MaLoaiDocGia)
)
GO
--Tao bang the loai sach
CREATE TABLE [THELOAISACH](
 [MaTheLoai] [int] NOT NULL,
 [TenTheLoai] [nvarchar]
(40) NULL,
CONSTRAINT [PK_THELOAISACH] PRIMARY KEY(MaTheLoai)
)
GO
--Tao bang sach mat
CREATE TABLE [SACHMAT](
 [MaSach] [int] NOT NULL,
 [NgayMat] [datetime] NULL,
 [TienPhatMatSach] [float] NULL,
 [MaDocGia] [int] NULL,
 [MaNhanVien] [int] NULL,
CONSTRAINT [PK_SACHMAT] PRIMARY KEY(MaSach)
)
GO
--Tạo bảng Tham số
CREATE TABLE [THAMSO](
 [TenThamSo] [nvarchar](40) NOT NULL,
 [GiaTri] [int] NULL,
CONSTRAINT [PK_THAMSO] PRIMARY KEY (TenThamSo)
)
GO
--Tạo bảng Lý do thanh lý
CREATE TABLE [LYDOTHANHLY](
 [MaLyDo] [int] NOT NULL,
 [TenLyDo] [nvarchar](20) NULL,
CONSTRAINT [PK_LYDOTHANHLY] PRIMARY KEY (MaLyDo)
)
GO
--Tạo bảng Chức vụ
CREATE TABLE [CHUCVU](
 [MaChucVu] [int] NOT NULL,
 [TenChucVu] [nvarchar](50) NULL,
CONSTRAINT [PK_CHUCVU] PRIMARY KEY (MaChucVu)
)
GO
--Tạo bảng Bằng cấp
CREATE TABLE [BANGCAP](
 [MaBangCap] [int] NOT NULL,
 [TenBangCap] [nvarchar](40) NULL,
CONSTRAINT [PK_BANGCAP] PRIMARY KEY (MaBangCap)
)
GO
--Tạo bảng Nhân viên
CREATE TABLE [NHANVIEN](
 [MaNhanVien] [int] NOT NULL,
 [HoTenNhanVien] [nvarchar](50) NULL,
 [NgaySinh] [datetime] NULL,
 [DiaChi] [nvarchar](50) NULL,
 [DienThoai] [nvarchar](15) NULL,
 [MaBangCap] [int] NULL,
 [MaBoPhan] [int] NULL,
 [MaChucVu] [int] NULL,
CONSTRAINT [PK_NHANVIEN] PRIMARY KEY (MaNhanVien)
)
GO
--Tạo bảng Độc giả
CREATE TABLE [DOCGIA](
 [MaDocGia] [int] NOT NULL,
 [HoTenDocGia] [nvarchar](40) NULL,
 [LoaiDocGia] [int] NULL,
 [NgaySinh] [datetime] NULL,
 [DiaChi] [nvarchar](50) NULL,
 [Email] [nvarchar](30) NULL,
 [NgayLapThe] [datetime] NULL,
 [NgayHetHan] [datetime] NULL,
 [MaNhanVien] [int] NULL,
 [TienNo] [float] NULL,
CONSTRAINT [PK_DOCGIA_1] PRIMARY KEY (MaDocGia)
)
GO
--Tạo bang chi tiet phieu thanh ly
CREATE TABLE [CHITIETPHIEUTHANHLY](
 [MaPhieuThanhLy] [int] NOT NULL,
 [MaSach] [int] NOT NULL,
 [MaLyDo] [int] NULL,
CONSTRAINT [PK_CHITIETPHIEUTHANHLY] PRIMARY KEY (MaPhieuThanhLy,MaSach) 
)
GO 
--Tạo bảng Phiếu thu tiền
CREATE TABLE [PHIEUTHUTIEN](
 [MaPhieuThuTien] [int] NOT NULL,
 [SoTienNo] [float] NULL,
 [SoTienThu] [float] NULL,
 [MaDocGia] [int] NULL,
 [MaNhanVien] [int] NULL,
CONSTRAINT [PK_PHIEUTHUTIEN] PRIMARY KEY (MaPhieuThuTien)
)
GO
--Tạo bảng Sách
CREATE TABLE [SACH](
 [MaSach] [int] NOT NULL,
 [TenSach] [nvarchar](40) NULL,
 [TacGia] [nvarchar](30) NULL,
 [NamXuatBan] [int] NULL,
 [NhaXuatBan] [nvarchar](40) NULL,
 [TriGia] [float] NULL,
 [MaNhanVien] [int] NULL,
 [MaTheLoai] [int] NULL,
 [SanSang] [bit] NULL,
 [NgayNhap] [datetime] NULL,
CONSTRAINT [PK_SACH] PRIMARY KEY (MaSach)
)
GO
--Tạo bảng Phiếu thanh lý
CREATE TABLE [PHIEUTHANHLY](
 [MaPhieuThanhLy] [int] NOT NULL,
 [NgayThanhLy] [datetime] NULL,
 [MaNhanVien] [int] NULL,
CONSTRAINT [PK_PHIEUTHANHLY] PRIMARY KEY (MaPhieuThanhLy)
)
GO
--Tạo bảng Phiếu mượn sách
CREATE TABLE [PHIEUMUONSACH](
 [MaPhieuMuon] [int] NOT NULL,
 [NgayMuon] [datetime] NOT NULL,
 [MaDocGia] [int] NULL,
CONSTRAINT [PK_PHIEUMUONSACH] PRIMARY KEY (MaPhieuMuon)
)
--Tạo bảng Chi tiết phiếu mượn
CREATE TABLE [CHITIETPHIEUMUON](
 [MaSach] [int] NOT NULL,
 [MaPhieuMuon] [int] NOT NULL,
CONSTRAINT [PK_CHITIETPHIEUMUON] PRIMARY KEY (MaSach,MaPhieuMuon)
)
GO
--Tạo khoa ngoai
GO
ALTER TABLE [NHANVIEN] WITH NOCHECK ADD CONSTRAINT [FK_NHANVIEN_BANGCAP] FOREIGN
KEY([MaBangCap])
REFERENCES [BANGCAP] ([MaBangCap])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_BANGCAP]
GO
ALTER TABLE [NHANVIEN] WITH NOCHECK ADD CONSTRAINT [FK_NHANVIEN_BOPHAN] FOREIGN
KEY([MaBoPhan])
REFERENCES [BOPHAN] ([MaBoPhan])
ON UPDATE CASCADE
ON DELETE CASCADE 
ALTER TABLE [NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_BOPHAN]
GO
ALTER TABLE [NHANVIEN] WITH NOCHECK ADD CONSTRAINT [FK_NHANVIEN_CHUCVU] FOREIGN
KEY([MaChucVu])
REFERENCES [CHUCVU] ([MaChucVu])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_CHUCVU]
GO
ALTER TABLE [DOCGIA] WITH NOCHECK ADD CONSTRAINT [FK_DOCGIA_LOAIDOCGIA] FOREIGN
KEY([LoaiDocGia])
REFERENCES [LOAIDOCGIA] ([MaLoaiDocGia])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [DOCGIA] CHECK CONSTRAINT [FK_DOCGIA_LOAIDOCGIA]
GO
ALTER TABLE [DOCGIA] WITH CHECK ADD CONSTRAINT [FK_DOCGIA_NHANVIEN] FOREIGN
KEY([MaNhanVien])
REFERENCES [NHANVIEN] ([MaNhanVien])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [DOCGIA] CHECK CONSTRAINT [FK_DOCGIA_NHANVIEN]
GO
ALTER TABLE [CHITIETPHIEUTHANHLY] WITH CHECK ADD CONSTRAINT
[FK_CHITIETPHIEUTHANHLY_LYDOTHANHLY] FOREIGN KEY([MaLyDo])
REFERENCES [LYDOTHANHLY] ([MaLyDo])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CHITIETPHIEUTHANHLY] CHECK CONSTRAINT
[FK_CHITIETPHIEUTHANHLY_LYDOTHANHLY]
GO
ALTER TABLE [CHITIETPHIEUTHANHLY] WITH CHECK ADD CONSTRAINT
[FK_CHITIETPHIEUTHANHLY_PHIEUTHANHLY] FOREIGN KEY([MaPhieuThanhLy])
REFERENCES [PHIEUTHANHLY] ([MaPhieuThanhLy])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CHITIETPHIEUTHANHLY] CHECK CONSTRAINT
[FK_CHITIETPHIEUTHANHLY_PHIEUTHANHLY]
GO
ALTER TABLE [PHIEUTHUTIEN] WITH CHECK ADD CONSTRAINT [FK_PHIEUTHUTIEN_DOCGIA]
FOREIGN KEY([MaDocGia])
REFERENCES [DOCGIA] ([MaDocGia])
GO
ALTER TABLE [PHIEUTHUTIEN] CHECK CONSTRAINT [FK_PHIEUTHUTIEN_DOCGIA]
GO
ALTER TABLE [PHIEUTHUTIEN] WITH CHECK ADD CONSTRAINT [FK_PHIEUTHUTIEN_NHANVIEN]
FOREIGN KEY([MaNhanVien])
REFERENCES [NHANVIEN] ([MaNhanVien])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [PHIEUTHUTIEN] CHECK CONSTRAINT [FK_PHIEUTHUTIEN_NHANVIEN]
GO
ALTER TABLE [SACH] WITH CHECK ADD CONSTRAINT [FK_SACH_NHANVIEN] FOREIGN
KEY([MaNhanVien])
REFERENCES [NHANVIEN] ([MaNhanVien])
ON UPDATE CASCADE
ON DELETE CASCADE 
GO
ALTER TABLE [SACH] CHECK CONSTRAINT [FK_SACH_NHANVIEN]
GO
ALTER TABLE [PHIEUTHANHLY] WITH CHECK ADD CONSTRAINT [FK_PHIEUTHANHLY_NHANVIEN]
FOREIGN KEY([MaNhanVien])
REFERENCES [NHANVIEN] ([MaNhanVien])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [PHIEUTHANHLY] CHECK CONSTRAINT [FK_PHIEUTHANHLY_NHANVIEN]
GO
ALTER TABLE [PHIEUMUONSACH] WITH CHECK ADD CONSTRAINT [FK_PHIEUMUONSACH_DOCGIA]
FOREIGN KEY([MaDocGia])
REFERENCES [DOCGIA] ([MaDocGia])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [PHIEUMUONSACH] CHECK CONSTRAINT [FK_PHIEUMUONSACH_DOCGIA]
GO
ALTER TABLE [CHITIETPHIEUMUON] WITH CHECK ADD CONSTRAINT
[FK_CHITIETPHIEUMUON_PHIEUMUONSACH] FOREIGN KEY([MaPhieuMuon])
REFERENCES [PHIEUMUONSACH] ([MaPhieuMuon])
GO
ALTER TABLE [CHITIETPHIEUMUON] CHECK CONSTRAINT
[FK_CHITIETPHIEUMUON_PHIEUMUONSACH]
GO
ALTER TABLE [CHITIETPHIEUMUON] WITH CHECK ADD CONSTRAINT
[FK_CHITIETPHIEUMUON_SACH] FOREIGN KEY([MaSach])
REFERENCES [SACH] ([MaSach])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CHITIETPHIEUMUON] CHECK CONSTRAINT [FK_CHITIETPHIEUMUON_SACH] 



--Nhap lieu
USE ThuVien
GO
INSERT INTO BANGCAP VALUES ('1',N'Tú tài')
INSERT INTO BANGCAP VALUES ('2',N'Trung cấp')
INSERT INTO BANGCAP VALUES ('3',N'Cao đẳng')
INSERT INTO BANGCAP VALUES ('4',N'Đại học')
INSERT INTO BANGCAP VALUES ('5',N'Thạc sĩ')
INSERT INTO BANGCAP VALUES ('6',N'Tiến sĩ')
INSERT INTO BANGCAP VALUES ('7',N'Nghiên cứu sinh')